version: '3'

services:
  teste-postgres-compose:
    image: postgis/postgis
    hostname: "postgres-sales-guide"
    container_name: postgres-sales-guide
    environment:
      POSTGRES_PASSWORD: "Postgres2019!"
      POSTGRES_USER: "admin"
    ports:
      - "15432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "renatogroff@yahoo.com.br"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - "16543:80"
    depends_on:
      - teste-postgres-compose
    networks:
      - postgres-compose-network

#  sales-guide-rabbitmq:
#    build:
#      context: ./rabbitmq
#      dockerfile: Dockerfile
#    hostname: "rabbitmq"
#    container_name: sales-guide-rabbitmq
#    ports:
#      - "15672:15672"
#      - "5672:5672"
#    labels:
#      NAME: "rabbitmq"
#    networks:
#      - sales-guide-network
#    environment:
#      - RABBITMQ_DEFAULT_USER=guest
#      - RABBITMQ_DEFAULT_PASS=guest
#
#  sales-guide-redis:
#    image: "redis:alpine"
#    hostname: "redis"
#    command: sh -c "redis-server --requirepass admin --appendonly yes"
#    container_name: sales-guide-redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - ./redis/storage:/data
#    environment:
#      - REDIS_REPLICATION_MODE=master
#    networks:
#      - sales-guide-network
#
#  sales-guide-redis-commander:
#    container_name: sales-guide-redis-commander
#    hostname: redis-commander
#    image: rediscommander/redis-commander:latest
#    environment:
#      - REDIS_HOST=redis
#      - REDIS_PORT=6379
#      - REDIS_PASSWORD=admin
#      - REDIS_DB=mycatalog
#    ports:
#      - "8081:8081"
#    networks:
#      - sales-guide-network
#
#  sales-guide-mongo-server-1:
#    image: mongo:latest
#    container_name: sales-guide-mongo-server-1
#    command: --port 27017
#    ports:
#      - 27017:27017
#    volumes:
#      - mongo-server-1-store:/data/db
#    networks:
#      - sales-guide-network

networks:
  postgres-compose-network:
    driver: bridge
  sales-guide-network:
    ipam:
      driver: default

volumes:
  postgres-data:
    driver: local
