version: "3.7"

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4571:4571"
      - "4566:4566"
    environment:
      -  DEFAULT_REGION=sa-east-1
      - SERVICES=s3,dynamodb,sqs,secretsmanager,stepfunctions,s3api,route53,rds
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
      - KINESIS_PROVIDER=kinesalite

    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"