version: "3.7"

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "443:443"
      - "53:53"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
      - "4571:4571"
      - "4566:4566"
      - "4510-4520:4510-4520"
    environment:
      - DEFAULT_REGION=sa-east-1
      - SERVICES=s3,dynamodb,sqs,secretsmanager,s3api,route53,kms,sns,cloudformation,eks,apigateway,lambda,cloudwatch,iam,ses,cognito-idp,cloudtrail,es,firehose,rds
      - DATA_DIR=/tmp/localstack/data
      - HOST_TMP_FOLDER=${TMPDIR}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
      - KINESIS_PROVIDER=kinesalite
      - LOCALSTACK_API_KEY=4utlOfXaWg
      - SMTP_HOST=smtp.gmail.com
      - SMTP_USER=estudo.async.hb@gmail.com
      - SMTP_PASS=Hbasync2018
      - SMTP_EMAIL=estudo.async.hb@gmail.com
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=1
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  stepfunctions:
    container_name: stepfunctions
    image: amazon/aws-stepfunctions-local:latest
    environment:
      - LAMBDA_ENDPOINT=http://localstack:4566
    ports:
      - '8083:8083'